<script setup lang="ts">
useHead({ title: 'About Kenya Tradex | Freight Forwarding & Logistics Company in Kenya', meta: [{ name: 'description', content: 'About Kenya Tradex, a Mombasa logistics company supporting freight forwarding, customs clearance and East African cargo movement.' }], link: [{ rel: 'canonical', href: 'https://kenyatradex.africa/about.html' }] })
</script>

<template>
  <!-- JOURNEY: Prospects use the about page to verify legitimacy before sharing cargo documents. The page foregrounds licenses, operating nodes, and the document-first way Kenya Tradex manages cargo risk. -->
  <SiteShell>
    <section class="hero"><NuxtImg class="hero-media" src="/images/customs-hero-1200.jpg" alt="Kenya Tradex logistics company" width="1600" height="900" /><div class="container hero-grid"><div><span class="eyebrow"><Icon class="ui-icon" name="lucide:building-2" aria-hidden="true" /> About Kenya Tradex</span><h1>Licensed freight forwarding and logistics support from Mombasa.</h1><p class="lead on-dark">Kenya Tradex supports importers, exporters, manufacturers, traders and project cargo teams moving goods through Kenya and into regional East African markets.</p></div><aside class="hero-card"><h2>Credentials</h2><ul><li><Icon class="ui-icon" name="lucide:circle-check" aria-hidden="true" /> KRA PIN: P051396680R</li><li><Icon class="ui-icon" name="lucide:circle-check" aria-hidden="true" /> KIFWA Member No: M2294</li><li><Icon class="ui-icon" name="lucide:circle-check" aria-hidden="true" /> Customs License: CAL/001526/24</li><li><Icon class="ui-icon" name="lucide:circle-check" aria-hidden="true" /> KPA No. 101839</li></ul></aside></div></section>
    <section class="section"><div class="container"><div class="features"><article class="feature"><Icon class="ui-icon feature-icon" name="lucide:anchor" aria-hidden="true" /><div><h3>Mombasa and Nairobi focus</h3><p>Operations are built around Port of Mombasa, Nairobi ICD and JKIA cargo workflows.</p></div></article><article class="feature"><Icon class="ui-icon feature-icon" name="lucide:route" aria-hidden="true" /><div><h3>Regional corridors</h3><p>Support extends to Uganda, Rwanda, Burundi, DRC, South Sudan and Tanzania.</p></div></article><article class="feature"><Icon class="ui-icon feature-icon" name="lucide:file-check-2" aria-hidden="true" /><div><h3>Document-first approach</h3><p>Practical cargo planning starts with the file: invoice, packing list, BL/AWB, permits and destination requirements.</p></div></article></div></div></section>
  </SiteShell>
</template>
