<script setup lang="ts">
definePageMeta({ layout: 'default' })

const { data: page } = await useAsyncData('page:about', () => queryCollection('pages').where('slug', '=', 'about').first())

if (!page.value) throw createError({ statusCode: 404, statusMessage: 'About Page Not Found' })

const blocks = computed(() => page.value?.blocks || [])
const featureBlocks = computed(() => blocks.value.filter((block) => block.type === 'list').slice(0, 3))
const detailBlocks = computed(() => blocks.value.filter((block) => !featureBlocks.value.includes(block)))

useSeoMeta(getEditablePageSeo(page.value))
useHead(getEditablePageHead(page.value))
</script>

<template>
  <!-- JOURNEY: Prospects use the about page to verify legitimacy before sharing cargo documents. The page foregrounds licenses, operating nodes, and the document-first way Kenya Tradex manages cargo risk. -->
  <div :data-content-id="page?.id">
    <section class="page-hero relative isolate overflow-hidden bg-[var(--color-brand-navy)] text-white"><NuxtImg class="absolute inset-0 z-[-2] h-full w-full object-cover" :src="page?.hero?.image || page?.image || '/images/customs-hero-1200.jpg'" :alt="page?.hero?.imageAlt || page?.hero?.heading || 'Kenya Tradex logistics company'" width="1600" height="900" /><div class="absolute inset-0 z-[-1] bg-[linear-gradient(120deg,oklch(16%_0.062_258/.94),oklch(22%_0.075_258/.78),oklch(42%_0.17_27/.38))]" /><div class="site-container grid items-end gap-10 lg:grid-cols-[1.35fr_.65fr]"><div><span class="inline-flex items-center gap-2 border-l-2 border-[var(--color-brand-red)] pl-3 text-sm font-bold uppercase tracking-[.12em] text-white/75"><Icon class="h-[1.1em] w-[1.1em] shrink-0" name="lucide:building-2" aria-hidden="true" /> Est. 2011 | Licensed Logistics Provider</span><h1 class="page-hero-title mt-5 text-white">{{ page?.hero?.heading || page?.title }}</h1><p class="mt-6 max-w-2xl text-lg text-white/85">{{ page?.hero?.lead || page?.description }}</p></div><aside class="border-t border-white/25 pt-5 lg:border-t-0 lg:border-l lg:pl-8 lg:pt-0"><p class="mb-4 text-xs font-bold uppercase tracking-[.16em] text-white/55">Trust indicators</p><ul class="m-0 list-none space-y-3 p-0"><li class="flex gap-3"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /> Since 2011</li><li class="flex gap-3"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /> Licensed provider</li><li class="flex gap-3"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /> Member of FIATA</li><li class="flex gap-3"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /> KIFWA Member No: M2294</li><li class="flex gap-3"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /> East Africa coverage</li></ul></aside></div></section>
    <section class="py-12 lg:py-20"><div class="site-container"><div class="grid gap-8 md:grid-cols-2 xl:grid-cols-3"><article v-for="(block, index) in featureBlocks" :key="block.title" class="border-t-4 border-[var(--color-brand-red)] bg-white p-5 text-[var(--color-text-primary)] sm:p-6"><Icon class="mb-5 h-8 w-8 text-[var(--color-brand-red)]" :name="['lucide:anchor', 'lucide:route', 'lucide:file-check-2'][index] || 'lucide:circle-check'" aria-hidden="true" /><h2 class="mb-3 text-2xl font-extrabold">{{ block.title }}</h2><p v-if="block.body" class="text-[var(--color-text-muted)]">{{ block.body }}</p><ul v-if="block.items?.length" class="mt-4 list-none space-y-2 p-0"><li v-for="item in block.items" :key="item" class="flex gap-2 text-sm text-[var(--color-text-muted)]"><Icon class="mt-1 h-4 w-4 shrink-0 text-[var(--color-brand-red)]" name="lucide:check" aria-hidden="true" />{{ item }}</li></ul></article></div></div></section>
    <section class="pb-12 lg:pb-20"><div class="site-container grid gap-x-12 md:grid-cols-2"><article v-for="block in detailBlocks" :key="block.title || block.body" class="content-flow border-b border-[var(--color-border)] py-8 text-[var(--color-text-primary)]"><h2 v-if="block.title" class="section-title">{{ block.title }}</h2><p v-if="block.body" class="text-[var(--color-text-muted)]">{{ block.body }}</p><p v-for="paragraph in block.paragraphs || []" :key="paragraph" class="text-[var(--color-text-muted)]">{{ paragraph }}</p><ul v-if="block.items?.length" class="m-0 list-none space-y-3 p-0"><li v-for="item in block.items" :key="item" class="flex gap-3 text-[var(--color-text-muted)]"><Icon class="mt-1 h-[1.1em] w-[1.1em] shrink-0 text-[var(--color-brand-red)]" name="lucide:circle-check" aria-hidden="true" /><span>{{ item }}</span></li></ul></article><section v-if="page?.faq?.length" class="mt-8 bg-[var(--color-harbor)] p-6 md:col-span-2 sm:p-8"><h2 class="section-title mb-5">Frequently asked questions</h2><details v-for="item in page.faq" :key="item.question" class="border-t border-[var(--color-border)] py-4"><summary class="cursor-pointer font-extrabold">{{ item.question }}</summary><p class="mt-3 text-[var(--color-text-muted)]">{{ item.answer }}</p></details></section></div></section>
  </div>
</template>
